# Login DB
db.login.url=jdbc:postgresql://localhost:5432/synonym_login_db
db.login.user=synonym
db.login.password=Synonym@123

# Files DB
db.files.url=jdbc:postgresql://localhost:5432/synonym_files_db
db.files.user=synonym
db.files.password=Synonym@123
